name: main_todo_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it:
  # Bloc for state management
  flutter_bloc:
  # Value equality
  equatable:
  # Functional programming thingies
  dartz:
  # Remote API
  connectivity:
  http:
  # Local cache
  shared_preferences:
  device_preview: ^1.1.0
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/task_detail.png
    - assets/images/stickman.png
    - assets/images/bg1.png
    - assets/images/bg2.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
